// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unity2D.Data;

#nullable disable

namespace Unity2D.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260428074500_SyncDB")]
    partial class SyncDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Unity2D.Item_instance", b =>
                {
                    b.Property<int>("Iid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Iid"));

                    b.Property<int>("Dup_count")
                        .HasColumnType("int");

                    b.Property<int>("Eid")
                        .HasColumnType("int");

                    b.Property<int>("Enhance_fail_count")
                        .HasColumnType("int");

                    b.Property<int>("Enhance_level")
                        .HasColumnType("int");

                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Iid");

                    b.HasIndex("Eid");

                    b.HasIndex("Id");

                    b.ToTable("item_instances");
                });

            modelBuilder.Entity("Unity2D.Item_master", b =>
                {
                    b.Property<int>("Eid")
                        .HasColumnType("int");

                    b.Property<double>("Base_armor")
                        .HasColumnType("double");

                    b.Property<double>("Base_atk")
                        .HasColumnType("double");

                    b.Property<double>("Base_hp")
                        .HasColumnType("double");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Eid");

                    b.ToTable("item_masters");

                    b.HasData(
                        new
                        {
                            Eid = 1,
                            Base_armor = 0.0,
                            Base_atk = 1.0,
                            Base_hp = 0.0,
                            Type = "weapon"
                        },
                        new
                        {
                            Eid = 2,
                            Base_armor = 0.0,
                            Base_atk = 1.0,
                            Base_hp = 0.0,
                            Type = "weapon"
                        },
                        new
                        {
                            Eid = 3,
                            Base_armor = 0.0,
                            Base_atk = 1.0,
                            Base_hp = 0.0,
                            Type = "weapon"
                        },
                        new
                        {
                            Eid = 4,
                            Base_armor = 0.0,
                            Base_atk = 1.0,
                            Base_hp = 0.0,
                            Type = "weapon"
                        },
                        new
                        {
                            Eid = 5,
                            Base_armor = 0.0,
                            Base_atk = 1.0,
                            Base_hp = 0.0,
                            Type = "weapon"
                        },
                        new
                        {
                            Eid = 6,
                            Base_armor = 0.0,
                            Base_atk = 1.0,
                            Base_hp = 0.0,
                            Type = "weapon"
                        },
                        new
                        {
                            Eid = 7,
                            Base_armor = 0.0,
                            Base_atk = 1.0,
                            Base_hp = 0.0,
                            Type = "weapon"
                        },
                        new
                        {
                            Eid = 8,
                            Base_armor = 0.0,
                            Base_atk = 1.0,
                            Base_hp = 0.0,
                            Type = "weapon"
                        },
                        new
                        {
                            Eid = 9,
                            Base_armor = 0.0,
                            Base_atk = 1.0,
                            Base_hp = 0.0,
                            Type = "weapon"
                        },
                        new
                        {
                            Eid = 10,
                            Base_armor = 0.0,
                            Base_atk = 1.0,
                            Base_hp = 0.0,
                            Type = "weapon"
                        },
                        new
                        {
                            Eid = 11,
                            Base_armor = 0.0,
                            Base_atk = 1.0,
                            Base_hp = 0.0,
                            Type = "weapon"
                        },
                        new
                        {
                            Eid = 12,
                            Base_armor = 0.0,
                            Base_atk = 1.0,
                            Base_hp = 0.0,
                            Type = "weapon"
                        },
                        new
                        {
                            Eid = 13,
                            Base_armor = 1.0,
                            Base_atk = 0.0,
                            Base_hp = 0.0,
                            Type = "armor"
                        },
                        new
                        {
                            Eid = 14,
                            Base_armor = 1.0,
                            Base_atk = 0.0,
                            Base_hp = 0.0,
                            Type = "armor"
                        },
                        new
                        {
                            Eid = 15,
                            Base_armor = 1.0,
                            Base_atk = 0.0,
                            Base_hp = 0.0,
                            Type = "armor"
                        },
                        new
                        {
                            Eid = 16,
                            Base_armor = 1.0,
                            Base_atk = 0.0,
                            Base_hp = 0.0,
                            Type = "armor"
                        },
                        new
                        {
                            Eid = 17,
                            Base_armor = 1.0,
                            Base_atk = 0.0,
                            Base_hp = 0.0,
                            Type = "armor"
                        },
                        new
                        {
                            Eid = 18,
                            Base_armor = 1.0,
                            Base_atk = 0.0,
                            Base_hp = 0.0,
                            Type = "armor"
                        },
                        new
                        {
                            Eid = 19,
                            Base_armor = 1.0,
                            Base_atk = 0.0,
                            Base_hp = 0.0,
                            Type = "armor"
                        },
                        new
                        {
                            Eid = 20,
                            Base_armor = 1.0,
                            Base_atk = 0.0,
                            Base_hp = 0.0,
                            Type = "armor"
                        },
                        new
                        {
                            Eid = 21,
                            Base_armor = 0.0,
                            Base_atk = 0.5,
                            Base_hp = 0.5,
                            Type = "accessory"
                        },
                        new
                        {
                            Eid = 22,
                            Base_armor = 0.0,
                            Base_atk = 0.5,
                            Base_hp = 0.5,
                            Type = "accessory"
                        },
                        new
                        {
                            Eid = 23,
                            Base_armor = 0.0,
                            Base_atk = 0.5,
                            Base_hp = 0.5,
                            Type = "accessory"
                        },
                        new
                        {
                            Eid = 24,
                            Base_armor = 0.0,
                            Base_atk = 0.5,
                            Base_hp = 0.5,
                            Type = "accessory"
                        },
                        new
                        {
                            Eid = 25,
                            Base_armor = 0.0,
                            Base_atk = 0.0,
                            Base_hp = 1.0,
                            Type = "extra"
                        },
                        new
                        {
                            Eid = 26,
                            Base_armor = 0.0,
                            Base_atk = 0.0,
                            Base_hp = 1.0,
                            Type = "extra"
                        });
                });

            modelBuilder.Entity("Unity2D.Log_enhance", b =>
                {
                    b.Property<int>("Lid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Lid"));

                    b.Property<int>("Currency_used")
                        .HasColumnType("int");

                    b.Property<int>("Iid")
                        .HasColumnType("int");

                    b.Property<int>("Level_after")
                        .HasColumnType("int");

                    b.Property<int>("Level_before")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Lid");

                    b.HasIndex("Iid");

                    b.ToTable("log_enhances");
                });

            modelBuilder.Entity("Unity2D.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Exp")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("players");
                });

            modelBuilder.Entity("Unity2D.Item_instance", b =>
                {
                    b.HasOne("Unity2D.Item_master", "Item_master")
                        .WithMany()
                        .HasForeignKey("Eid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unity2D.Player", "Player")
                        .WithMany()
                        .HasForeignKey("Id");

                    b.Navigation("Item_master");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Unity2D.Log_enhance", b =>
                {
                    b.HasOne("Unity2D.Item_instance", "Item_instance")
                        .WithMany("Log_enhance")
                        .HasForeignKey("Iid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item_instance");
                });

            modelBuilder.Entity("Unity2D.Item_instance", b =>
                {
                    b.Navigation("Log_enhance");
                });
#pragma warning restore 612, 618
        }
    }
}
