name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ] # 사용하는 브랜치 이름(main 또는 master)으로 맞춰주세요.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 1. 내 코드 가져오기
      uses: actions/checkout@v4

    - name: 2. AWS 서버로 전체 코드 전송 (SCP)
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2 }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        source: "."
        target: "/home/ubuntu/game-backend"

    - name: 3. AWS 서버 접속 후 Docker 빌드 및 실행
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2 }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd /home/ubuntu/game-backend
          
          # 새 버전의 도커 이미지 빌드
          sudo docker build -t game-server .
          
          # 기존에 돌아가던 구버전 서버가 있다면 정지 및 삭제
          sudo docker stop game-server-container || true
          sudo docker rm game-server-container || true
          
          # 환경 변수(DB 문자열)를 주입하며 새 서버 실행
          sudo docker run -d \
            --name game-server-container \
            -p 8080:8080 \
            -e ConnectionStrings__DefaultConnection="${{ secrets.DB_CONNECTION }}" \
	    -e Jwt__Key="${{ secrets.JWT_SECRET_KEY }}" \
            game-server